name: CI Pipeline 
on: [pull_request]
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '18'
    - name: Install dependencies
      run: npm Install
    - name: Run tests
      run: npm test